<?php
/**
 * Slider - Shortcode Options
 */
add_action( 'init', 'slider_vc_map' );
if ( ! function_exists( 'slider_vc_map' ) ) {
  function slider_vc_map() {
    vc_map( array(
    "name" => __( "Slider", 'segovia-core'),
    "base" => "segovia_slider",
    "description" => __( "Slider Style", 'segovia-core'),
    "icon" => "fa fa-sliders color-pink",
    "category" => SegoviaLib::segovia_cat_name(),
    "params" => array(       

      // List
      array(
        'type' => 'param_group', 
        'value' => '',
        'heading' => __( 'Slider', 'segovia-core' ),
        'param_name' => 'sliders',
        // Note params is mapped inside param-group:
        'params' => array(      
          array(
            'type' => 'attach_image',
            'value' => '',
            'heading' => __( 'Upload Background Image', 'segovia-core' ),
            'param_name' => 'slider_image',
            'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          ),
          array(
            'type' => 'dropdown',
            'heading' => __( 'Caption Content Alignment', 'segovia-core' ),
            'value' => array(
              __( 'Select The Alignment', 'segovia-core' ) => '',
              __( 'Left', 'segovia-core' ) => 'left',
              __( 'Right', 'segovia-core' ) => 'right',
              __( 'Center', 'segovia-core' ) => 'center',
            ),
            'param_name' => 'caption_alignment',
            'description' => __( 'Select your alignment.', 'segovia-core' ),
            'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          ),            
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Slider Title', 'segovia-core' ),
            'admin_label' => true,
            'param_name' => 'slider_title',
          ),
          array(
            'type' => 'dropdown',
            'heading' => __( 'Title Animation', 'segovia-core' ),
            'value' => array(
              __( 'fadeInDown', 'segovia-core' )          => 'fadeInDown',
              __( 'bounce', 'segovia-core' )              => 'bounce',
              __( 'flash', 'segovia-core' )               => 'flash',
              __( 'pulse', 'segovia-core' )               => 'pulse',
              __( 'rubberBand', 'segovia-core' )          => 'rubberBand',
              __( 'shake', 'segovia-core' )               => 'shake',
              __( 'swing', 'segovia-core' )               => 'swing',
              __( 'tada', 'segovia-core' )                => 'tada',
              __( 'wobble', 'segovia-core' )              => 'wobble',
              __( 'jello', 'segovia-core' )               => 'jello',
              __( 'bounceIn', 'segovia-core' )            => 'bounceIn',
              __( 'bounceInDown', 'segovia-core' )        => 'bounceInDown',
              __( 'bounceInLeft', 'segovia-core' )        => 'bounceInLeft',
              __( 'bounceInRight', 'segovia-core' )       => 'bounceInRight',
              __( 'bounceInUp', 'segovia-core' )          => 'bounceInUp',
              __( 'bounceOut', 'segovia-core' )           => 'bounceOut',
              __( 'bounceOutDown', 'segovia-core' )       => 'bounceOutDown',
              __( 'bounceOutLeft', 'segovia-core' )       => 'bounceOutLeft',
              __( 'bounceOutRight', 'segovia-core' )      => 'bounceOutRight',
              __( 'bounceOutUp', 'segovia-core' )         => 'bounceOutUp',
              __( 'fadeIn', 'segovia-core' )              => 'fadeIn',
              __( 'fadeInDownBig', 'segovia-core' )       => 'fadeInDownBig',
              __( 'fadeInLeft', 'segovia-core' )          => 'fadeInLeft',
              __( 'fadeInLeftBig', 'segovia-core' )       => 'fadeInLeftBig',
              __( 'fadeInRight', 'segovia-core' )         => 'fadeInRight',
              __( 'fadeInRightBig', 'segovia-core' )      => 'fadeInRightBig',
              __( 'fadeInUp', 'segovia-core' )            => 'fadeInUp',
              __( 'fadeInUpBig', 'segovia-core' )         => 'fadeInUpBig',
              __( 'fadeOut', 'segovia-core' )             => 'fadeOut',
              __( 'fadeOutDown', 'segovia-core' )         => 'fadeOutDown',
              __( 'fadeOutDownBig', 'segovia-core' )      => 'fadeOutDownBig',
              __( 'fadeOutLeft', 'segovia-core' )         => 'fadeOutLeft',
              __( 'fadeOutLeftBig', 'segovia-core' )      => 'fadeOutLeftBig',
              __( 'fadeOutRight', 'segovia-core' )        => 'fadeOutRight',
              __( 'fadeOutRightBig', 'segovia-core' )     => 'fadeOutRightBig',
              __( 'fadeOutUp', 'segovia-core' )           => 'fadeOutUp',
              __( 'fadeOutUpBig', 'segovia-core' )        => 'fadeOutUpBig',
              __( 'flip', 'segovia-core' )                => 'flip',
              __( 'flipInX', 'segovia-core' )             => 'flipInX',
              __( 'flipInY', 'segovia-core' )             => 'flipInY',
              __( 'flipOutX', 'segovia-core' )            => 'flipOutX',
              __( 'flipOutY', 'segovia-core' )            => 'flipOutY',
              __( 'lightSpeedIn', 'segovia-core' )        => 'lightSpeedIn',
              __( 'lightSpeedOut', 'segovia-core' )       => 'lightSpeedOut',
              __( 'rotateIn', 'segovia-core' )            => 'rotateIn',
              __( 'rotateInDownLeft', 'segovia-core' )    => 'rotateInDownLeft',
              __( 'rotateInDownRight', 'segovia-core' )   => 'rotateInDownRight',
              __( 'rotateInUpLeft', 'segovia-core' )      => 'rotateInUpLeft',
              __( 'rotateInUpRight', 'segovia-core' )     => 'rotateInUpRight',
              __( 'rotateOut', 'segovia-core' )           => 'rotateOut',
              __( 'rotateOutDownLeft', 'segovia-core' )   => 'rotateOutDownLeft',
              __( 'rotateOutDownRight', 'segovia-core' )  => 'rotateOutDownRight',
              __( 'rotateOutUpLeft', 'segovia-core' )     => 'rotateOutUpLeft',
              __( 'rotateOutUpRight', 'segovia-core' )    => 'rotateOutUpRight',
              __( 'slideInUp', 'segovia-core' )           => 'slideInUp',
              __( 'slideInDown', 'segovia-core' )         => 'slideInDown',
              __( 'slideInLeft', 'segovia-core' )         => 'slideInLeft',
              __( 'slideInRight', 'segovia-core' )        => 'slideInRight',
              __( 'slideOutUp', 'segovia-core' )          => 'slideOutUp',
              __( 'slideOutDown', 'segovia-core' )        => 'slideOutDown',
              __( 'slideOutLeft', 'segovia-core' )        => 'slideOutLeft',
              __( 'slideOutRight', 'segovia-core' )       => 'slideOutRight',
              __( 'zoomIn', 'segovia-core' )              => 'zoomIn',
              __( 'zoomInDown', 'segovia-core' )          => 'zoomInDown',
              __( 'zoomInLeft', 'segovia-core' )          => 'zoomInLeft',
              __( 'zoomInRight', 'segovia-core' )         => 'zoomInRight',
              __( 'zoomInUp', 'segovia-core' )            => 'zoomInUp',
              __( 'zoomOut', 'segovia-core' )             => 'zoomOut',
              __( 'zoomOutDown', 'segovia-core' )         => 'zoomOutDown',
              __( 'zoomOutLeft', 'segovia-core' )         => 'zoomOutLeft',
              __( 'zoomOutRight', 'segovia-core' )        => 'zoomOutRight',
              __( 'zoomOutUp', 'segovia-core' )           => 'zoomOutUp',
              __( 'hinge', 'segovia-core' )               => 'hinge',
              __( 'jackInTheBox', 'segovia-core' )        => 'jackInTheBox',
              __( 'rollIn', 'segovia-core' )              => 'rollIn',
              __( 'rollOut', 'segovia-core' )             => 'rollOut',
            ),
            'param_name' => 'title_animation',
            'description' => __( 'Select your animation.', 'segovia-core' ),
          ),  
          array(
            'type' => 'textarea',
            'value' => '',
            'heading' => __( 'Slider Content', 'segovia-core' ),
            'param_name' => 'slider_content',
          ), 
          array(
            'type' => 'dropdown',
            'heading' => __( 'Content Animation', 'segovia-core' ),
            'value' => array(
              __( 'fadeInDown', 'segovia-core' )          => 'fadeInDown',
              __( 'bounce', 'segovia-core' )              => 'bounce',
              __( 'flash', 'segovia-core' )               => 'flash',
              __( 'pulse', 'segovia-core' )               => 'pulse',
              __( 'rubberBand', 'segovia-core' )          => 'rubberBand',
              __( 'shake', 'segovia-core' )               => 'shake',
              __( 'swing', 'segovia-core' )               => 'swing',
              __( 'tada', 'segovia-core' )                => 'tada',
              __( 'wobble', 'segovia-core' )              => 'wobble',
              __( 'jello', 'segovia-core' )               => 'jello',
              __( 'bounceIn', 'segovia-core' )            => 'bounceIn',
              __( 'bounceInDown', 'segovia-core' )        => 'bounceInDown',
              __( 'bounceInLeft', 'segovia-core' )        => 'bounceInLeft',
              __( 'bounceInRight', 'segovia-core' )       => 'bounceInRight',
              __( 'bounceInUp', 'segovia-core' )          => 'bounceInUp',
              __( 'bounceOut', 'segovia-core' )           => 'bounceOut',
              __( 'bounceOutDown', 'segovia-core' )       => 'bounceOutDown',
              __( 'bounceOutLeft', 'segovia-core' )       => 'bounceOutLeft',
              __( 'bounceOutRight', 'segovia-core' )      => 'bounceOutRight',
              __( 'bounceOutUp', 'segovia-core' )         => 'bounceOutUp',
              __( 'fadeIn', 'segovia-core' )              => 'fadeIn',
              __( 'fadeInDownBig', 'segovia-core' )       => 'fadeInDownBig',
              __( 'fadeInLeft', 'segovia-core' )          => 'fadeInLeft',
              __( 'fadeInLeftBig', 'segovia-core' )       => 'fadeInLeftBig',
              __( 'fadeInRight', 'segovia-core' )         => 'fadeInRight',
              __( 'fadeInRightBig', 'segovia-core' )      => 'fadeInRightBig',
              __( 'fadeInUp', 'segovia-core' )            => 'fadeInUp',
              __( 'fadeInUpBig', 'segovia-core' )         => 'fadeInUpBig',
              __( 'fadeOut', 'segovia-core' )             => 'fadeOut',
              __( 'fadeOutDown', 'segovia-core' )         => 'fadeOutDown',
              __( 'fadeOutDownBig', 'segovia-core' )      => 'fadeOutDownBig',
              __( 'fadeOutLeft', 'segovia-core' )         => 'fadeOutLeft',
              __( 'fadeOutLeftBig', 'segovia-core' )      => 'fadeOutLeftBig',
              __( 'fadeOutRight', 'segovia-core' )        => 'fadeOutRight',
              __( 'fadeOutRightBig', 'segovia-core' )     => 'fadeOutRightBig',
              __( 'fadeOutUp', 'segovia-core' )           => 'fadeOutUp',
              __( 'fadeOutUpBig', 'segovia-core' )        => 'fadeOutUpBig',
              __( 'flip', 'segovia-core' )                => 'flip',
              __( 'flipInX', 'segovia-core' )             => 'flipInX',
              __( 'flipInY', 'segovia-core' )             => 'flipInY',
              __( 'flipOutX', 'segovia-core' )            => 'flipOutX',
              __( 'flipOutY', 'segovia-core' )            => 'flipOutY',
              __( 'lightSpeedIn', 'segovia-core' )        => 'lightSpeedIn',
              __( 'lightSpeedOut', 'segovia-core' )       => 'lightSpeedOut',
              __( 'rotateIn', 'segovia-core' )            => 'rotateIn',
              __( 'rotateInDownLeft', 'segovia-core' )    => 'rotateInDownLeft',
              __( 'rotateInDownRight', 'segovia-core' )   => 'rotateInDownRight',
              __( 'rotateInUpLeft', 'segovia-core' )      => 'rotateInUpLeft',
              __( 'rotateInUpRight', 'segovia-core' )     => 'rotateInUpRight',
              __( 'rotateOut', 'segovia-core' )           => 'rotateOut',
              __( 'rotateOutDownLeft', 'segovia-core' )   => 'rotateOutDownLeft',
              __( 'rotateOutDownRight', 'segovia-core' )  => 'rotateOutDownRight',
              __( 'rotateOutUpLeft', 'segovia-core' )     => 'rotateOutUpLeft',
              __( 'rotateOutUpRight', 'segovia-core' )    => 'rotateOutUpRight',
              __( 'slideInUp', 'segovia-core' )           => 'slideInUp',
              __( 'slideInDown', 'segovia-core' )         => 'slideInDown',
              __( 'slideInLeft', 'segovia-core' )         => 'slideInLeft',
              __( 'slideInRight', 'segovia-core' )        => 'slideInRight',
              __( 'slideOutUp', 'segovia-core' )          => 'slideOutUp',
              __( 'slideOutDown', 'segovia-core' )        => 'slideOutDown',
              __( 'slideOutLeft', 'segovia-core' )        => 'slideOutLeft',
              __( 'slideOutRight', 'segovia-core' )       => 'slideOutRight',
              __( 'zoomIn', 'segovia-core' )              => 'zoomIn',
              __( 'zoomInDown', 'segovia-core' )          => 'zoomInDown',
              __( 'zoomInLeft', 'segovia-core' )          => 'zoomInLeft',
              __( 'zoomInRight', 'segovia-core' )         => 'zoomInRight',
              __( 'zoomInUp', 'segovia-core' )            => 'zoomInUp',
              __( 'zoomOut', 'segovia-core' )             => 'zoomOut',
              __( 'zoomOutDown', 'segovia-core' )         => 'zoomOutDown',
              __( 'zoomOutLeft', 'segovia-core' )         => 'zoomOutLeft',
              __( 'zoomOutRight', 'segovia-core' )        => 'zoomOutRight',
              __( 'zoomOutUp', 'segovia-core' )           => 'zoomOutUp',
              __( 'hinge', 'segovia-core' )               => 'hinge',
              __( 'jackInTheBox', 'segovia-core' )        => 'jackInTheBox',
              __( 'rollIn', 'segovia-core' )              => 'rollIn',
              __( 'rollOut', 'segovia-core' )             => 'rollOut',
            ),
            'param_name' => 'textarea_animation',
            'description' => __( 'Select your animation.', 'segovia-core' ),
          ),         
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Button Text', 'segovia-core' ),
            'param_name' => 'slider_link_text',
          ), 
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Button Link', 'segovia-core' ),
            'param_name' => 'slider_link',
          ), 
          array(
            'type' => 'dropdown',
            'heading' => __( 'Button Animation', 'segovia-core' ),
            'value' => array(
              __( 'fadeInDown', 'segovia-core' )          => 'fadeInDown',
              __( 'bounce', 'segovia-core' )              => 'bounce',
              __( 'flash', 'segovia-core' )               => 'flash',
              __( 'pulse', 'segovia-core' )               => 'pulse',
              __( 'rubberBand', 'segovia-core' )          => 'rubberBand',
              __( 'shake', 'segovia-core' )               => 'shake',
              __( 'swing', 'segovia-core' )               => 'swing',
              __( 'tada', 'segovia-core' )                => 'tada',
              __( 'wobble', 'segovia-core' )              => 'wobble',
              __( 'jello', 'segovia-core' )               => 'jello',
              __( 'bounceIn', 'segovia-core' )            => 'bounceIn',
              __( 'bounceInDown', 'segovia-core' )        => 'bounceInDown',
              __( 'bounceInLeft', 'segovia-core' )        => 'bounceInLeft',
              __( 'bounceInRight', 'segovia-core' )       => 'bounceInRight',
              __( 'bounceInUp', 'segovia-core' )          => 'bounceInUp',
              __( 'bounceOut', 'segovia-core' )           => 'bounceOut',
              __( 'bounceOutDown', 'segovia-core' )       => 'bounceOutDown',
              __( 'bounceOutLeft', 'segovia-core' )       => 'bounceOutLeft',
              __( 'bounceOutRight', 'segovia-core' )      => 'bounceOutRight',
              __( 'bounceOutUp', 'segovia-core' )         => 'bounceOutUp',
              __( 'fadeIn', 'segovia-core' )              => 'fadeIn',
              __( 'fadeInDownBig', 'segovia-core' )       => 'fadeInDownBig',
              __( 'fadeInLeft', 'segovia-core' )          => 'fadeInLeft',
              __( 'fadeInLeftBig', 'segovia-core' )       => 'fadeInLeftBig',
              __( 'fadeInRight', 'segovia-core' )         => 'fadeInRight',
              __( 'fadeInRightBig', 'segovia-core' )      => 'fadeInRightBig',
              __( 'fadeInUp', 'segovia-core' )            => 'fadeInUp',
              __( 'fadeInUpBig', 'segovia-core' )         => 'fadeInUpBig',
              __( 'fadeOut', 'segovia-core' )             => 'fadeOut',
              __( 'fadeOutDown', 'segovia-core' )         => 'fadeOutDown',
              __( 'fadeOutDownBig', 'segovia-core' )      => 'fadeOutDownBig',
              __( 'fadeOutLeft', 'segovia-core' )         => 'fadeOutLeft',
              __( 'fadeOutLeftBig', 'segovia-core' )      => 'fadeOutLeftBig',
              __( 'fadeOutRight', 'segovia-core' )        => 'fadeOutRight',
              __( 'fadeOutRightBig', 'segovia-core' )     => 'fadeOutRightBig',
              __( 'fadeOutUp', 'segovia-core' )           => 'fadeOutUp',
              __( 'fadeOutUpBig', 'segovia-core' )        => 'fadeOutUpBig',
              __( 'flip', 'segovia-core' )                => 'flip',
              __( 'flipInX', 'segovia-core' )             => 'flipInX',
              __( 'flipInY', 'segovia-core' )             => 'flipInY',
              __( 'flipOutX', 'segovia-core' )            => 'flipOutX',
              __( 'flipOutY', 'segovia-core' )            => 'flipOutY',
              __( 'lightSpeedIn', 'segovia-core' )        => 'lightSpeedIn',
              __( 'lightSpeedOut', 'segovia-core' )       => 'lightSpeedOut',
              __( 'rotateIn', 'segovia-core' )            => 'rotateIn',
              __( 'rotateInDownLeft', 'segovia-core' )    => 'rotateInDownLeft',
              __( 'rotateInDownRight', 'segovia-core' )   => 'rotateInDownRight',
              __( 'rotateInUpLeft', 'segovia-core' )      => 'rotateInUpLeft',
              __( 'rotateInUpRight', 'segovia-core' )     => 'rotateInUpRight',
              __( 'rotateOut', 'segovia-core' )           => 'rotateOut',
              __( 'rotateOutDownLeft', 'segovia-core' )   => 'rotateOutDownLeft',
              __( 'rotateOutDownRight', 'segovia-core' )  => 'rotateOutDownRight',
              __( 'rotateOutUpLeft', 'segovia-core' )     => 'rotateOutUpLeft',
              __( 'rotateOutUpRight', 'segovia-core' )    => 'rotateOutUpRight',
              __( 'slideInUp', 'segovia-core' )           => 'slideInUp',
              __( 'slideInDown', 'segovia-core' )         => 'slideInDown',
              __( 'slideInLeft', 'segovia-core' )         => 'slideInLeft',
              __( 'slideInRight', 'segovia-core' )        => 'slideInRight',
              __( 'slideOutUp', 'segovia-core' )          => 'slideOutUp',
              __( 'slideOutDown', 'segovia-core' )        => 'slideOutDown',
              __( 'slideOutLeft', 'segovia-core' )        => 'slideOutLeft',
              __( 'slideOutRight', 'segovia-core' )       => 'slideOutRight',
              __( 'zoomIn', 'segovia-core' )              => 'zoomIn',
              __( 'zoomInDown', 'segovia-core' )          => 'zoomInDown',
              __( 'zoomInLeft', 'segovia-core' )          => 'zoomInLeft',
              __( 'zoomInRight', 'segovia-core' )         => 'zoomInRight',
              __( 'zoomInUp', 'segovia-core' )            => 'zoomInUp',
              __( 'zoomOut', 'segovia-core' )             => 'zoomOut',
              __( 'zoomOutDown', 'segovia-core' )         => 'zoomOutDown',
              __( 'zoomOutLeft', 'segovia-core' )         => 'zoomOutLeft',
              __( 'zoomOutRight', 'segovia-core' )        => 'zoomOutRight',
              __( 'zoomOutUp', 'segovia-core' )           => 'zoomOutUp',
              __( 'hinge', 'segovia-core' )               => 'hinge',
              __( 'jackInTheBox', 'segovia-core' )        => 'jackInTheBox',
              __( 'rollIn', 'segovia-core' )              => 'rollIn',
              __( 'rollOut', 'segovia-core' )             => 'rollOut',
            ),
            'param_name' => 'btn_animation',
            'description' => __( 'Select your animation.', 'segovia-core' ),
          ), 
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Custom Class', 'segovia-core' ),
            'param_name' => 'custom_class',
          ),    
        ),
        
      ),
      SegoviaLib::vt_class_option(),

      // Design 
         array(
        "type"        =>'textfield',
        "heading"     =>__('Title Text Size', 'segovia-core'),
        "param_name"  => "title_size",
        "value"       => "",
        "group"       => __('Design', 'segovia-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),    
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Title Color', 'segovia-core'),
        "param_name"  => "title_color",
        "value"       => "",
        "group"       => __('Design', 'segovia-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Content Text Size', 'segovia-core'),
        "param_name"  => "content_text_size",
        "value"       => "",
        "group"       => __('Design', 'segovia-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Content Color', 'segovia-core'),
        "param_name"  => "content_color",
        "value"       => "",
        "group"       => __('Design', 'segovia-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),

      array(
        "type"        =>'textfield',
        "heading"     =>__('Button Text Size', 'segovia-core'),
        "param_name"  => "btn_text_size",
        "value"       => "",
        "group"       => __('Design', 'segovia-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Text Color', 'segovia-core'),
        "param_name"  => "btn_text_color",
        "value"       => "",
        "group"       => __('Design', 'segovia-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Text Hover Color', 'segovia-core'),
        "param_name"  => "btn_text_hover_color",
        "value"       => "",
        "group"       => __('Design', 'segovia-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Border Color', 'segovia-core'),
        "param_name"  => "btn_border_color",
        "value"       => "",
        "group"       => __('Design', 'segovia-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      ), // Params
    ) );
  }
}